/**
* This file contains utilities and functions related to catalog.
*
* Note: catalog.js & catalog.min.js are auto-generated by the script that convert csv into javascript dictionary, so its
* not easy adding extra functionality / processing to it. That's why we have a separated file for that.
*
* Note: this file is included once from the master loader html.
*
* Author: Ronen Ness.
* Since: 2016.
*/

// create the catalog utils namespace
window.DemoSite.CatalogUtils =  {

    // init the catalog utils
    init: function()
    {
        // create and init a dictionaries to lookup product by id or category
        this.by_id = {};
        this.by_category = {};
        for (var i = 0; i < DemoSite.Catalog.length; ++i)
        {
            // get current product
            var curr = DemoSite.Catalog[i];

            // add to by-id dict
            this.by_id[curr.product_id] = curr;

            // add to by-category dict
            if (curr.categories)
            {
                for (var c = 0; c < curr.categories.length; ++c)
                {
                    var cat = curr.categories[c];
                    this.by_category[cat] = this.by_category[cat] || [];
                    this.by_category[cat].push(curr);
                }
            }
        }
    },

    // get product by id
    get_product: function(id)
    {
        return this.by_id(id);
    },

}

// call catalog utils init
DemoSite.CatalogUtils.init();